name: Go CI Test

# Kích hoạt khi có push hoặc pull request vào nhánh main
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps: 
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Show Current Branch
          run: |
            echo "Full Ref: ${{ github.ref }}"
            echo "Branch Name: ${{ github.ref_name }}"

            if [ "${{ github.ref_name }}" = "main" ]; then
              echo "This is MAIN"
            else
              echo "This is DEV"
            fi

    # steps:
    #   # Bước 1: Lấy code từ repo
    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   # Bước 2: Cài đặt môi trường Go
    #   - name: Set up Go
    #     uses: actions/setup-go@v5
    #     with:
    #       go-version: '1.22'
    #       cache: true # Tự động cache dependency để chạy nhanh hơn

    #   # Bước 3: Kiểm tra lỗi cú pháp (Linter)
    #   - name: Verify dependencies
    #     run: go mod verify

    #   # Bước 4: Build project
    #   - name: Build
    #     run: go build -v ./...

    #   # Bước 5: Chạy Unit Test
    #   - name: Run Tests
    #     run: go test -v ./...

  golang-ci-check:
    name: Run Go Checks on Local Runner
    runs-on: self-hosted          # Chỉ định chạy trên máy local của bạn

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Bước 1: Kiểm tra định dạng code (Format)
      - name: Check Code Formatting
        run: |
          if [ -n "$FORMAT_ISSUES" ]; then
            echo "Các file sau chưa được format đúng chuẩn 'go fmt':"
            echo "$FORMAT_ISSUES"
            exit 1
          fi
          

      # Bước 2: Chạy Go Vet để bắt lỗi logic tĩnh
      - name: Run Go Vet
        run: go vet ./...